// <auto-generated />
using System;
using GentlmenBot.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GentlmenBot.Migrations
{
    [DbContext(typeof(GentlemenContext))]
    [Migration("20221126165255_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("GentlmenBot.Context.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnglishCources")
                        .HasColumnType("TEXT");

                    b.Property<int>("EnglishCourcesCostCoverage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LineManager")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPeoplePartner")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("NextPerfomanceReview")
                        .HasColumnType("TEXT");

                    b.Property<string>("PossibleMentor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
